spring:  
    profiles:  
        active: -dev
---
spring:  
    profiles: dev
    application: 
        name:  microservicecloud-config-mfw-dev
---
spring:  
    profiles:  test
    application: 
        name:  microservicecloud-config-mfw-test
