spring:  
    profiles:  
        active: -dev
---
server: 
   port: 8001
mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml
   type-aliases-package: com.mfw.springcloud.entity
   mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
   profiles: dev
   application:
      name: microservicecloud-dept-config-client
   datasource: 
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/cloudDB01?useSSL=false&characterEncoding=utf-8
      username: root
      password: 123456
      dbcp2:
         min-idle: 5
         initial-size: 5
         max-total: 5
         max-wait-millis: 2000000
eureka:
   client: 
      serviceUrl:
         defaultZone: http://eureka7001:7001/eureka
   instance:
      instance-id: microservicecloud-dept8001
      prefer-ip-address: true
info: 
   app.name: mfw-microservicecloud
   company.name: www.mfw.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
---
server: 
   port: 8001
mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml
   type-aliases-package: com.mfw.springcloud.entity
   mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
   profiles: test
   application:
      name: microservicecloud-dept-config-client
   datasource: 
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/cloudDB03?useSSL=false&characterEncoding=utf-8
      username: root
      password: 123456
      dbcp2:
         min-idle: 5
         initial-size: 5
         max-total: 5
         max-wait-millis: 2000000
eureka:
   client: 
      serviceUrl:
         defaultZone: http://eureka7001:7001/eureka
   instance:
      instance-id: microservicecloud-dept8001
      prefer-ip-address: true
info: 
   app.name: mfw-microservicecloud
   company.name: www.mfw.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$